[learning_config]
repo_url = "https://github.com/your_username/your_repo"
repo_branch = "main"
github_token = "your_github_token_here"

[llm_config]
api_max_token_limitation = 100000000

[llm_config.code_model]
host = "api.example.com"
model = "Qwen3-235b-A22b"
url = "/api/v1/"
key = "your_api_key_here"
timeout = 50

[llm_config.embedding_model]
host = "api.example.com"
model = "Qwen3-Embedding-8B"
url = "/api/v1/"
key = "your_api_key_here"
timeout = 50

[llm_config.reranker_model]
host = "api.example.com"
model = "Qwen3-Reranker-8B"
url = "/api/v1/"
key = "your_api_key_here"
timeout = 50